<a href="https://colab.research.google.com/github/Sabri3299/M-L-Project/blob/M-L/Stress_Level_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm

In [ ]:
from google.colab import files
files.upload()

Saving Stress-Lysis (1).csv to Stress-Lysis (1).csv


{'Stress-Lysis (1).csv': b'Humidity,Temperature,Step_count,Stress_Level\r\n21.33,90.33,123,1\r\n21.41,90.41,93,1\r\n27.12,96.12,196,2\r\n27.64,96.64,177,2\r\n10.87,79.87,87,0\r\n11.31,80.31,40,0\r\n18.16,87.16,88,1\r\n28.2,97.2,162,2\r\n14.25,83.25,61,0\r\n26.13,95.13,168,2\r\n23.61,92.61,200,2\r\n19.37,88.37,117,1\r\n29.08,98.08,179,2\r\n17.83,86.83,55,1\r\n28.06,97.06,148,2\r\n19.43,88.43,123,1\r\n26.85,95.85,169,2\r\n26.51,95.51,135,2\r\n29.49,98.49,149,2\r\n20.94,89.94,122,1\r\n28.6,97.6,131,2\r\n18.62,87.62,43,1\r\n14.43,83.43,79,0\r\n26.69,95.69,153,2\r\n15.67,84.67,21,1\r\n26.63,95.63,147,2\r\n17.58,86.58,30,1\r\n21.53,90.53,105,1\r\n20.99,89.99,127,1\r\n23.94,92.94,162,2\r\n19.06,88.06,87,1\r\n25.46,94.46,172,2\r\n29.19,98.19,190,2\r\n28.73,97.73,144,2\r\n21.69,90.69,121,1\r\n23.66,92.66,134,2\r\n19.51,88.51,93,1\r\n14.84,83.84,29,0\r\n15.34,84.34,79,1\r\n20.76,89.76,104,1\r\n28.08,97.08,150,2\r\n14.23,83.23,59,0\r\n20,89,104,1\r\n13.13,82.13,40,0\r\n21.96,90.96,110,1\r\n24.84,

In [ ]:
stress=pd.read_csv('Stress-Lysis (1).csv')
stress

Humidity  Temperature  Step_count  Stress_Level
0        21.33        90.33         123             1
1        21.41        90.41          93             1
2        27.12        96.12         196             2
3        27.64        96.64         177             2
4        10.87        79.87          87             0
...        ...          ...         ...           ...
1996     21.82        90.82          96             1
1997     10.45        79.45          45             0
1998     27.22        96.22         135             2
1999     12.46        81.46          64             0
2000     16.87        85.87          50             1

[2001 rows x 4 columns]

In [ ]:
print(stress.head())
print(stress.shape)

   Humidity  Temperature  Step_count  Stress_Level
0     21.33        90.33         123             1
1     21.41        90.41          93             1
2     27.12        96.12         196             2
3     27.64        96.64         177             2
4     10.87        79.87          87             0
(2001, 4)


In [ ]:
stress.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Humidity      2001 non-null   float64
 1   Temperature   2001 non-null   float64
 2   Step_count    2001 non-null   int64  
 3   Stress_Level  2001 non-null   int64  
dtypes: float64(2), int64(2)
memory usage: 62.7 KB


In [ ]:
stress.isnull().sum()

Humidity        0
Temperature     0
Step_count      0
Stress_Level    0
dtype: int64

In [ ]:
X=stress.drop('Stress_Level',axis=1)
Y=stress['Stress_Level']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=1)
X_train

Humidity  Temperature  Step_count
846      12.10        81.10          28
536      28.19        97.19         161
231      18.93        87.93          74
727      25.80        94.80         135
38       15.34        84.34          79
...        ...          ...         ...
112      18.53        87.53          34
1439     27.25        96.25         138
1688     22.35        91.35         111
533      23.07        92.07         146
146      28.62        97.62         133

[1800 rows x 3 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)
print(X_train)
print(X_test)

[[-1.36569792 -1.36569792 -1.23475399]
 [ 1.41610501  1.41610501  1.05450142]
 [-0.18485802 -0.18485802 -0.44298144]
 ...
 [ 0.40642638  0.40642638  0.19387909]
 [ 0.53090731  0.53090731  0.79631472]
 [ 1.49044779  1.49044779  0.57255291]]
[[-1.23115899 -1.23115899 -1.34249966]
 [-0.628454   -0.628454   -1.68336043]
 [ 1.22171012  1.22171012  1.33325741]
 [ 1.23572652  1.23572652  1.46960172]
 [ 0.34743749  0.34743749  0.15728775]
 [ 0.25633092  0.25633092 -0.0813148 ]
 [ 0.82224287  0.82224287  1.07761183]
 [-0.02574902 -0.02574902  0.41293333]
 [ 0.66631047  0.66631047  0.77083714]
 [-0.81417124 -0.81417124 -0.38808949]
 [ 0.39299077  0.39299077 -0.04722872]
 [ 0.16872846  0.16872846  0.36180421]
 [ 1.19367733  1.19367733  1.0605688 ]
 [-1.2031262  -1.2031262  -1.06981104]
 [ 1.19893348  1.19893348  1.11169791]
 [-0.64071835 -0.64071835 -0.25174518]
 [-1.56755246 -1.56755246 -1.51293005]
 [-1.32576965 -1.32576965 -0.71190723]
 [ 1.27952775  1.27952775  0.68562194]
 [-0.68451958 -0.68

In [ ]:
from sklearn.linear_model import LogisticRegression
logReg=LogisticRegression()
logReg.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
X_train_prediction=logReg.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('accuracy on training data:',training_data_accuracy)
X_test_prediction=logReg.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('accuracy on test data:',test_data_accuracy)

accuracy on training data: 0.9983333333333333
accuracy on test data: 1.0


In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier().fit(X_train,Y_train)

In [ ]:
X_train_prediction=dtc.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('accuracy on training data:',training_data_accuracy)
X_test_prediction=dtc.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('accuracy on test data:',test_data_accuracy)

accuracy on training data: 1.0
accuracy on test data: 0.9950248756218906


In [ ]:
knn=KNeighborsClassifier().fit(X_train,Y_train)

In [ ]:
X_train_prediction=knn.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('accuracy on training data:',training_data_accuracy)
X_test_prediction=knn.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('accuracy on test data:',test_data_accuracy)

accuracy on training data: 1.0
accuracy on test data: 1.0


In [ ]:
gnB=GaussianNB().fit(X_train,Y_train)

In [ ]:
X_train_prediction=gnB.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('accuracy on training data:',training_data_accuracy)
X_test_prediction=gnB.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('accuracy on test data:',test_data_accuracy)

accuracy on training data: 0.99
accuracy on test data: 1.0


In [ ]:
svm=svm.SVC(kernel='linear')
svm.fit(X_train,Y_train)

SVC(kernel='linear')

In [ ]:
X_train_prediction=svm.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('accuracy on training data:',training_data_accuracy)
X_test_prediction=svm.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('accuracy on test data:',test_data_accuracy)

accuracy on training data: 0.9988888888888889
accuracy on test data: 1.0


In [ ]:
input_data=(27.64,96.64,177)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=dtc.predict(input_data_reshaped)
print(prediction[0])
if (prediction==1):
  print('Moderate')
elif prediction ==2:
  print('High')
else:
  print('Low')

2
High
